// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package decisionQuerier

import (
	"database/sql"

	"github.com/google/uuid"
)

type Decision struct {
	ID                  uuid.UUID
	ActorUserID         uuid.UUID
	RecipientUserID     uuid.UUID
	LikedRecipient      bool
	RecipientLikesActor bool
	CreatedAt           sql.NullTime
}
