// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package decisionQuerier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Count(ctx context.Context, arg CountParams) (int64, error)
	GetOneByActorUserId(ctx context.Context, actorUserID uuid.UUID) (Decision, error)
	GetOneByRecipientUserID(ctx context.Context, recipientUserID uuid.UUID) (Decision, error)
	List(ctx context.Context, arg ListParams) ([]Decision, error)
	UpsertOne(ctx context.Context, arg UpsertOneParams) (Decision, error)
}

var _ Querier = (*Queries)(nil)
